### PR TITLE
[Edited] Form after Feedback round 2

### PR DESCRIPTION
**Pull request by Saralrat**
1.Made changes to the form from feedback received.

- Edit form Quotation and Sales Order
http://redmine.ecosoft.co.th:10083/issues/5708

- Edit form Purchase Order
http://redmine.ecosoft.co.th:10083/issues/5712

- Edit form Purchase Receipt
http://redmine.ecosoft.co.th:10083/issues/5770

- Edit form Expense Claims
http://redmine.ecosoft.co.th:10083/issues/5771

- Edit form Sales Invoice
http://redmine.ecosoft.co.th:10083/issues/5791

- Edit form Receipt
http://redmine.ecosoft.co.th:10083/issues/5792

- Edit form Sales Billing
http://redmine.ecosoft.co.th:10083/issues/5793

- Edit form Credit Note
http://redmine.ecosoft.co.th:10083/issues/5794

### CODE REVIEW

**Comment by newtratip** [comment]
Could you rename ตรายาง-menghua-book.png to eng language ?

**Comment by newtratip** [comment]
required_apps should add all depend app such as kittiu/sales_billing

**Comment by newtratip** [comment]
required_apps should add all depend app such as kittiu/sales_billing

**Comment by Saralrat** [comment]
> Could you rename ตรายาง-menghua-book.png to eng language ?

I've edited it.

**Comment by Saralrat** [comment]
> required_apps should add all depend app such as kittiu/sales_billing

I've edited it.

**Pull request merged**
